language: bash
services: docker

branches: 
  only: 
    - master

install:
  - docker build -t eswork/jenkins .
  
script: 
  - docker run --name jenkins -d --restart=always eswork/jenkins; sleep 5
  - docker ps -a | grep -q jenkins
